# Generated by Django 4.2.7 on 2023-12-16 04:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('envelope_id', models.AutoField(primary_key=True, serialize=False)),
                ('envelope_name', models.CharField(max_length=200)),
                ('envelope_query_date', models.DateField(default=datetime.date(2023, 12, 18), null=True)),
                ('envelope_due_date', models.DateField(blank=True, null=True)),
                ('envelope_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
