# Generated by Django 4.2.7 on 2023-11-25 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('envelope_id', models.AutoField(primary_key=True, serialize=False)),
                ('envelope_name', models.CharField(max_length=200)),
                ('envelope_members', models.ManyToManyField(related_name='user_envelopes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
