# Generated by Django 4.2.7 on 2023-12-08 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_invitation_group_name_group_id_group_key_and_more'),
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='envelope_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2023, 12, 10), null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_members',
            field=models.ManyToManyField(to='board.group'),
        ),
    ]
