# Generated by Django 4.2.7 on 2023-12-08 23:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_remove_invitation_group_name_group_envelope_id_and_more'),
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='envelope_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envelope',
            name='envelope_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2023, 12, 10), null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_members',
            field=models.ManyToManyField(to='board.group'),
        ),
    ]
