# Generated by Django 4.2.7 on 2023-12-07 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='envelope_due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='envelope_query_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 12, 0)),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_members',
            field=models.ManyToManyField(to='board.group'),
        ),
    ]
