# Generated by Django 4.2.7 on 2024-01-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='questions_default',
            field=models.ManyToManyField(blank=True, to='question.defaultquestionenvelope'),
        ),
    ]
