# Generated by Django 4.2.7 on 2023-12-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_alter_envelope_envelope_query_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='envelope_members',
        ),
    ]
