# Generated by Django 4.2.7 on 2023-12-09 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_envelope_envelope_admin_envelope_envelope_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2023, 12, 11), null=True),
        ),
    ]
