# Generated by Django 4.2.7 on 2023-12-08 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_envelope_envelope_due_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_due_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_datetime',
            field=models.DateField(default=datetime.date(2023, 12, 10), null=True),
        ),
    ]
