# Generated by Django 4.2.7 on 2023-12-08 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0003_alter_envelope_envelope_due_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelope',
            old_name='envelope_due_datetime',
            new_name='envelope_due_date',
        ),
        migrations.RenameField(
            model_name='envelope',
            old_name='envelope_query_datetime',
            new_name='envelope_query_date',
        ),
    ]
