# Generated by Django 5.0.1 on 2024-01-08 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0004_alter_envelope_envelope_query_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2024, 1, 9), null=True),
        ),
    ]
