# Generated by Django 4.2.7 on 2023-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0004_alter_envelope_envelope_query_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='envelope_frequency',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
