# Generated by Django 4.2.9 on 2024-01-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0005_alter_envelope_envelope_query_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
