# Generated by Django 4.2.7 on 2023-12-24 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0005_envelope_envelope_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='envelope_issue',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2023, 12, 26), null=True),
        ),
    ]
