# Generated by Django 4.2.9 on 2024-01-10 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0006_envelope_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_query_date', models.CharField(blank=True, max_length=50, null=True)),
                ('email_query_date', models.CharField(blank=True, max_length=50, null=True)),
                ('email_due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('email_admin_next_issue', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='envelope',
            name='envelope_query_date_future',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2024, 1, 12), null=True),
        ),
    ]
