# Generated by Django 4.2.7 on 2023-12-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_basequestion_envelope_issue_number'),
        ('envelope', '0006_envelope_envelope_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='user_answers',
            field=models.ManyToManyField(blank=True, to='question.answer'),
        ),
    ]
