# Generated by Django 4.2.7 on 2023-12-25 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0007_envelope_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2023, 12, 27), null=True),
        ),
    ]
