# Generated by Django 4.2.9 on 2024-01-13 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0007_datemanager_envelope_envelope_query_date_future_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelope',
            old_name='envelope_query_date_future',
            new_name='change_envelope_query_date',
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2024, 1, 15), null=True),
        ),
    ]
