# Generated by Django 4.2.9 on 2024-01-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0009_rename_change_query_date_datemanager_change_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='change_envelope_query_date',
        ),
        migrations.AddField(
            model_name='envelope',
            name='date_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='envelope.datemanager'),
        ),
    ]
