# Generated by Django 4.2.9 on 2024-01-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0010_remove_envelope_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemanager',
            old_name='change_dates',
            new_name='change_due_date',
        ),
        migrations.RenameField(
            model_name='datemanager',
            old_name='email_admin_next_issue',
            new_name='change_issue_number',
        ),
        migrations.RenameField(
            model_name='datemanager',
            old_name='email_due_date',
            new_name='change_query_date',
        ),
        migrations.RemoveField(
            model_name='datemanager',
            name='email_query_date',
        ),
    ]
