# Generated by Django 4.2.7 on 2023-12-31 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0010_alter_envelope_envelope_query_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='questions_admin',
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2024, 1, 2), null=True),
        ),
    ]
