# Generated by Django 4.2.7 on 2024-01-01 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0011_remove_envelope_questions_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_query_date',
            field=models.DateField(default=datetime.date(2024, 1, 3), null=True),
        ),
    ]
