# Generated by Django 4.2.7 on 2023-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequestion',
            name='envelope_issue_number',
            field=models.IntegerField(default=1),
        ),
    ]
