# Generated by Django 4.2.7 on 2024-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_defaultquestionenvelope_default_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
