# Generated by Django 4.2.7 on 2023-12-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_basequestion_envelope_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
