# Generated by Django 4.2.7 on 2023-12-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0011_remove_envelope_questions_admin_and_more'),
        ('question', '0004_alter_basequestion_is_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminQuestion',
        ),
    ]
