# Generated by Django 4.2.7 on 2024-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_answer_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='display_name',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
