# Generated by Django 4.2.7 on 2023-12-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0003_remove_envelope_envelope_members'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='envelope_id',
        ),
        migrations.AddField(
            model_name='group',
            name='envelope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='envelope.envelope'),
            preserve_default=False,
        ),
    ]
