# Generated by Django 4.2.7 on 2023-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='display_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
