# Generated by Django 4.2.7 on 2023-12-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_invitation_group_name_group_envelope_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
    ]
