# Generated by Django 4.2.7 on 2023-12-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_usergroup_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_invitations',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='invitation',
        ),
    ]
