# Generated by Django 4.2.7 on 2023-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_group_envelope_id_group_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='is_invited',
            field=models.BooleanField(default=True),
        ),
    ]
