# Generated by Django 4.2.7 on 2023-12-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_usergroup_is_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='is_invited',
        ),
    ]
