# Generated by Django 4.2.7 on 2023-12-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0003_alter_envelope_envelope_query_date'),
        ('board', '0003_remove_group_group_invitations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='envelope',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='envelope.envelope'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
