# Generated by Django 4.2.7 on 2023-12-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_usergroup_group_usergroup_envelope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='env_id',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
